require('./container.test');
require('./easyAttrs.test');
require('./destroy.test');
require('./object.test');
require('./properties.test');
require('./aliases.test');
require('./applyAttributeNs.test');
require('./backbone.test');
require('./index.test');